name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout PatternFly Java
        id: checkout-patternfly-java
        uses: actions/checkout@v4
        with:
          repository: patternfly-java/patternfly-java
          path: patternfly-java
      - name: Checkout PatternFly Showcase (1)
        id: checkout-patternfly-showcase-1
        uses: actions/checkout@v4
        with:
          path: patternfly-showcase
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Install PatternFly Java
        id: install-patternfly-java
        run: $MVN install
        working-directory: patternfly-java
      - name: Package PatternFly Showcase
        id: install-patternfly-showcase
        run: $MVN install
        working-directory: patternfly-showcase
      - name: Backup Pages
        id: backup-pages
        run: mv patternfly-showcase/target/showcase /tmp/showcase
      - name: Checkout PatternFly Showcase (2)
        id: checkout-patternfly-showcase-2
        uses: actions/checkout@v4
      - name: Restore Pages
        id: restore-pages
        run: mv /tmp/showcase ./target
      - name: Publish PatternFly Showcase
        id: publish-patternfly-showcase
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: ./target/showcase
          clean: true
