name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  patternfly-java:
    name: Install PatternFly Java
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: patternfly-java/patternfly-java
          path: patternfly-java
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Install
        id: install
        run: $MVN install
        working-directory: patternfly-java

  patternfly-showcase:
    name: Build PatternFly Showcase
    runs-on: ubuntu-latest
    needs: patternfly-java
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          path: patternfly-showcase
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Install
        id: install
        run: $MVN install
        working-directory: patternfly-showcase

  pages:
    name: Publish PatternFly Showcase
    runs-on: ubuntu-latest
    needs: patternfly-showcase
    steps:
      - name: Publish
        id: publish
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: ./patternfly-showcase/target/showcase
          clean: true
