name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout PatternFly Java
        id: checkout-patternfly-java
        uses: actions/checkout@v4
        with:
          repository: patternfly-java/patternfly-java
          path: patternfly-java
      - name: Checkout PatternFly Showcase
        id: checkout-patternfly-showcase
        uses: actions/checkout@v4
        with:
          path: patternfly-showcase
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Install PatternFly Java
        id: install-patternfly-java
        run: $MVN install
        working-directory: patternfly-java
      - name: Verify PatternFly Showcase
        id: verify-patternfly-showcase
        run: $MVN verify
        working-directory: patternfly-showcase
